version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Or your preferred Node.js version
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building React app...
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: "build"

cache:
  paths:
    - "node_modules/**/*"
